# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-views', '-viewed', 'added'],
                'get_latest_by': 'viewed',
            },
        ),
        migrations.AlterUniqueTogether(
            name='viewtracker',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
